### PR TITLE
add swift 5.8 & 5.9 workflow

### PR DESCRIPTION
**Pull request by samisuteria**
Also ran swiftformat since the workflow was failing.

### CODE REVIEW

**Review by NeedleInAJayStack — APPROVED** [review]
Ugh, thanks for running the formatter. It's frustrating that it doesn't seem to stay consistent across versions.

Thanks!

**Comment by NeedleInAJayStack** [comment]
@samisuteria Hey, I made some CI changes to fix the MacOS runner. Would you mind rebasing on main and add in the Swift 5.8 again? Thanks again for these changes.

**Comment by samisuteria** [comment]
@NeedleInAJayStack made the changes :)

**Review by NeedleInAJayStack — APPROVED** [review]
Thanks!

**Pull request merged**
