### PR TITLE
Preserve result order

### PR DESCRIPTION
**Pull request by NeedleInAJayStack**
PR to align Graphiti with this GraphQL PR: https://github.com/GraphQLSwift/GraphQL/issues/60

@adam-fowler Heads up - I reverted the swift-tools-version because [this](http://openradar.appspot.com/FB7691693) issue is still present in XCode 12.4. This means that anyone with XCode < 12.5 cannot build Graphiti, even if they are using a Swift 5.4 toolchain.

### CODE REVIEW

**Comment by NeedleInAJayStack** [comment]
This will fail until we update GraphQL dependencies

**Comment by adam-fowler** [comment]
@NeedleInAJayStack this doesn't make sense you are saying you can build this package with swift 5.2 even though you can't.

**Comment by NeedleInAJayStack** [comment]
@adam-fowler Yes, I know. I'm trying to find the path of least resistance on working around the XCode bug (I have coworkers who don't often update XCode, they just update their toolchain). If you disagree with changing this here, I understand and will change it back to 5.4.

**Comment by NeedleInAJayStack** [comment]
@adam-fowler I've changed the `swift-tools-version` back to 5.4. Thanks for the discussion!

**Pull request merged**
