### PR TITLE
GraphQL v3

### PR DESCRIPTION
**Pull request by NeedleInAJayStack**
This adds compatibility with [GraphQL v3.0.0](https://github.com/GraphQLSwift/GraphQL/releases/tag/3.0.0), and removes `TypeReference` since it is no longer necessary.

This will result in a major version bump.

### CODE REVIEW

**Review by paulofaria — APPROVED** [review]
Awesome work!!! Since this is a major bump, I think it would be nice to highlight the new features in the README.

**Comment by NeedleInAJayStack** [comment]
Sorry Paulo - I should have drafted this one. I've added a migration guide, and deleted deprecated features.

I still have a little validation testing to do before I want to call this ready.

**Comment by NeedleInAJayStack** [comment]
Ok, my validation is complete - sorry about the delay. Since your last review @paulofaria, I added a [migration guide](https://github.com/GraphQLSwift/Graphiti/pull/147/commits/1f356743ccc9ebcf7cada4e1aeb390dd2db8abad), similar to what we did for the GraphQL repo. Let me know if that addresses your thoughts! Thanks!

**Comment by NeedleInAJayStack** [comment]
@paulofaria Just a ping on this!

**Review by paulofaria — APPROVED** [review]

**Comment by NeedleInAJayStack** [comment]
@zamderax We've merged and I tagged as [v2.0.0](https://github.com/GraphQLSwift/Graphiti/releases/tag/2.0.0) just now!

**Pull request merged**
