### PR TITLE
Scalar customizations

### PR DESCRIPTION
**Pull request by NeedleInAJayStack**
This allows clients to fully customize the `serialize`, `parseValue`, and `parseLiteral` behavior of a scalar at declaration time. This allows more complex scalars (such as untyped JSON) to be implemented on top of Graphiti.

[This repo](https://github.com/NeedleInAJayStack/GraphQLJSONScalar)'s needs were a motivation for these changes.

This is a minor version bump

### CODE REVIEW

**Comment by NeedleInAJayStack** [comment]
Hey @paulofaria, any thoughts or concerns about this change?

**Comment by NeedleInAJayStack** [comment]
Hey @paulofaria, do you have a bit of time for a code review on this?

**Review by paulofaria — APPROVED** [review]

**Comment by paulofaria** [comment]
Sorry for the extremely long delay!

**Comment by NeedleInAJayStack** [comment]
No worries! Thanks Paulo!

**Pull request merged**
