### PR TITLE
Fixes github CI for automated testing

### PR DESCRIPTION
**Pull request by NeedleInAJayStack**

### CODE REVIEW

**Comment by NeedleInAJayStack** [comment]
@paulofaria The CI failure is caused by the multithreading bug that this GraphQL pull request fixes: https://github.com/GraphQLSwift/GraphQL/pull/76

**Comment by paulofaria** [comment]
Can you please update from master?

**Comment by NeedleInAJayStack** [comment]
> Can you please update from master?

Yup, done!

**Comment by paulofaria** [comment]
Thanks! @NeedleInAJayStack 😄

**Pull request merged**
