### PR TITLE
Made inits public for NoArguments and PageInfo

### PR DESCRIPTION
**Pull request by cshadek**
Addresses #124 to make inits public for both PageInfo and NoArguments.  This should help with custom connections and enable people to call resolvers with no arguments directly.

### CODE REVIEW

**Comment by cshadek** [comment]
@NeedleInAJayStack I don't know why macOS is failing, but I also fixed swiftformat warnings in `ConnectionTests`.  The only real changes I made are making the inits public.

**Review by NeedleInAJayStack — APPROVED** [review]
Looks great! Thanks @cshadek!

It appears that the MacOS failure is related to codeclimate: https://github.com/GraphQLSwift/Graphiti/actions/runs/6512886544/job/17691405715?pr=126#step:4:7956
@paulofaria, do you have any insight or would you prefer if we disable the codeclimate integration?

**Comment by cshadek** [comment]
@NeedleInAJayStack, @paulofaria is it possible to approve this merge even with macOS failing?

**Comment by paulofaria** [comment]
Is codeclimate still being used for test coverage? I don't remember if test coverage checks are required by the SSWG maturity level we're going for?

**Comment by cshadek** [comment]
Is it possible to expedite this?  We are trying to have custom connections in addition to the graffiti ones, and both need access to PageInfo

**Comment by NeedleInAJayStack** [comment]
@cshadek Sure, we can merge this in since the CI shows that no tests are failing on MacOS. If you have any free cycles, we'd sure love some help either fixing the codeclimate CI or finding a different test coverage solution (I've been super slammed with other things recently). But yeah, don't want it to hold you up in the meantime.

**Comment by cshadek** [comment]
@NeedleInAJayStack Thanks!  I'll look into it.  Not too familiar with codeclimate, but I'll see what I can do!

**Pull request merged**
