### PR TITLE
Introduce EventLoopFutures!

### PR DESCRIPTION
**Pull request by kimdv**
Need to make new release [GraphQL#41](https://github.com/GraphQLSwift/GraphQL/pull/41) to update Package.swift properly.

### CODE REVIEW

**Comment by paulofaria** [comment]
can you please update this to GraphQL 0.6.0 instead of master?

**Comment by paulofaria** [comment]
Oh and point it to GraphQLSwift/GraphQL of course.

**Comment by paulofaria** [comment]
Also looks like the build failed on macOS.

**Comment by kimdv** [comment]
Just fixed some warnings and loosed swift version requirement (The reason for the failing macOS test)

**Pull request merged**
