### PR TITLE
Adds a SchemaBuilder type for modular schema creation

### PR DESCRIPTION
**Pull request by NeedleInAJayStack**
This adds a `SchemaBuilder`, which enables much more modular schema creation. By breaking up the schema definition, different parts of the schema could be created in different functions, files, or even packages.

### CODE REVIEW

**Comment by paulofaria** [comment]
Are these additive changes? Didn't have enough time to properly look into it, yet.

**Comment by NeedleInAJayStack** [comment]
Yup, purely additive.

**Comment by paulofaria** [comment]
Have you tried implementing it using result builders? I think it fits better with Swift when comparing it to [fluent builders](https://en.m.wikipedia.org/wiki/Fluent_interface).

**Comment by NeedleInAJayStack** [comment]
Can you split up result builder definitions or do they always need to be defined in a single contiguous block?

I'll admit, I'm not a result builder expert. My goal with this was to allow schemas to be defined over a number of different functions, files, or even packages, because my schema definitions get REALLY huge and unwieldy when I have to keep them in a single block. Builders like [Vapor's RouteBuilder](https://github.com/vapor/vapor/blob/main/Sources/Vapor/Routing/RoutesBuilder.swift) or [SQLKit's SQLPredicateBuilder](https://github.com/vapor/sql-kit/blob/main/Sources/SQLKit/Builders/SQLPredicateBuilder.swift) achieve that goal pretty well. For example, we could have a project with the 3 files below, where functionality is separated effectively:

```swift
# API.swift

let builder = SchemaBuilder<Res, Ctx>()
addHello(to: builder)
addGoodbye(to: builder)
let schema = try builder.build()
```

```swift
# Hello.swift

extension Res {
    func hello() -> String {
        "world"
    }
} 
func addHello(to builder: SchemaBuilder<Res, Ctx>) {
    builder.addQuery(
        Field("hello", at: Resolver.hello)
    )
}
```
```swift
# Goodbye.swift

extension Res {
    func goodbye() -> String {
        "for now"
    }
} 
func addGoodbye(to builder: SchemaBuilder<Res, Ctx>) {
    builder.addQuery(
        Field("goodbye", at: Resolver.goodbye)
    )
}
```

I didn't know how to accomplish something like this with a `resultBuilder` pattern. If there is one, could you provide me a quick example?

**Comment by paulofaria** [comment]
Hey, Jay! Sure, I'll give you an update this week!

**Comment by NeedleInAJayStack** [comment]
Hey @paulofaria, any updates on this? I'd be happy to make the changes if you can get me an example of the multi-file result-builder schema construction!

**Comment by paulofaria** [comment]
Sorry! I'm moving to a new house, so things are chaotic around here. I'll try to find the time, though. Should be straight forward.

**Comment by paulofaria** [comment]
Hey, @NeedleInAJayStack. Can you please check you reddit DMs? 😁

**Comment by cshadek** [comment]
Any updates on this?

**Comment by NeedleInAJayStack** [comment]
I think @paulofaria was going to send me an example of a distributed ResultBuilder

**Comment by paulofaria** [comment]
Really sorry about the delay. @NeedleInAJayStack can I update this PR directly, with the result builder approach? I think it's easier.

**Comment by NeedleInAJayStack** [comment]
@paulofaria No worries! Sure, feel free to edit this directly or on your own branch of my work.

**Comment by paulofaria** [comment]
Hey, I’m really sorry about this. I think it’s best to merge this as is and improve later, if necessary.

**Review by paulofaria — DISMISSED** [review]
LGTM

**Comment by NeedleInAJayStack** [comment]
Awesome, thanks Paulo! Mind approving again after my rebase?

**Review by paulofaria — APPROVED** [review]

**Comment by paulofaria** [comment]
@NeedleInAJayStack thank you very much for this, Jay!

**Pull request merged**
